#!/usr/bin/env node
var argv = require('yargs')
    .option('n', {
        alias: 'name',
        demand: true,
        default: 'zhaodan',
        describe: 'your name',
        type: 'string'
    })
    .argv

console.log('hello ' + argv.n)